Extract warn

diff --git a/monico b/monico
--- a/monico
+++ b/monico
@@ -20,6 +20,10 @@ version() {
   echo "$version"
 }
 
+warn() {
+  echo "${0##*/}: $*"
+}
+
 monitor() {
   inotifywait \
     --event 'create,delete,modify,move' \
@@ -83,7 +87,7 @@ while [[ $# -gt 0 ]]; do
       ;;
     -d|--directory)
       if [[ $# -lt 2 ]]; then
-        echo "${0##*/}: option requires an argument -- '${1##*-}'" >&2
+        warn "option requires an argument -- '${1##*-}'" >&2
         exit 2
       fi
       directory="$2"
@@ -108,7 +112,7 @@ while [[ $# -gt 0 ]]; do
       break
       ;;
     -*)
-      echo "${0##*/}: unrecognized option -- '${1##*-}'" >&2
+      warn "unrecognized option -- '${1##*-}'" >&2
       exit 2
       ;;
     *)
@@ -122,11 +126,11 @@ require_clear="${require_clear:-true}"
 directory="${directory:-$(pwd)}"
 
 if [[ $# -lt 1 ]]; then
-  echo "${0##*/}: no specify cmd" >&2
+  warn "no specify cmd" >&2
   exit 2
 fi
 if [[ -z $(type -- "$1" 2> /dev/null) ]]; then
-  echo "${0##*/}: $1: cannot execute" >&2
+  warn "$1: cannot execute" >&2
   exit 2
 fi
 cmd="$1"
